{{- with .Values.startUpJob -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: start-job
spec:
  #ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: start-job-sa
      automountServiceAccountToken: true
      containers:
      - name: start-container
        image: {{.image}}
        command: 
          {{toYaml .command |   nindent 12  }}
        args:
          {{- range .args }}
            - {{ . | quote}}
          {{- end}} 
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: start-job-sa
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-rw-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding
subjects:
- kind: ServiceAccount
  name: start-job-sa
  namespace: {{$.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: deployment-rw-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
