{{- $root := $ -}}
{{- $nodes := default  .Values.nodeJobs .Values.nodes }}
{{if and  ($nodes) (gt (len $nodes) 0) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{include "simulated-network.fullname" $root}}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-rw-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{include "simulated-network.fullname" $root}}
  namespace: {{$.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: deployment-rw-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}