{{- $root := $ -}}
{{- $nodes := default .Values.nodes .Values.nodeJobs }}
{{- range  $nodes }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- include "simulated-network.labels" $root | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{printf "%s-%s" "http" .name}}
      protocol: TCP
      name: http
    - port: 8888
      targetPort: {{printf "%s-%s" "tcp" .name}}
      name: tcp
  selector:
    app.kubernetes.io/name: {{ .name }}
---
{{- end -}}