# imagePullSecrets:
image:
  repository: ubuntu
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: image-pull-secret
resources: {}
configmap:
  graphivz.dot: |
    graph G {
      3 -- 4;
      2 -- 1;
      4 -- 1;
      4 -- 2;
      3 -- 2;
      1 -- 3;
    }
  node_list: |
    1 node1:8888
    2 node2:8888
    3 node4:8888
    4 node4:8888


livenessProbe:
  tcpSocket:
    port: 8888
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 8888
  initialDelaySeconds: 15
  periodSeconds: 10

nodes:
  - name: "node2"
    config: 
      neighbours: |
        node1
        node2
    command: ["/bin/bash","-c","--"]
    args: 
     #- "echo hello" 
      - "-c" 
      - "python -u node.py -id 1 -g  /etc/config/graphviz.dot -p /etc/config/node_list -t 9999"
    env:
      - name: POSTGRES_HOST
        value: postgres-host
  - name: node1
    config: {}
    command: ["/bin/bash","-c","--"]
    args: [ "while true; do sleep 30; done;" ]